#!/usr/bin/env python3
"""Turn an 8-pixel-wide BDF font into src/gfx/font.bend.

Each glyph is 16 rows of 8 bits, packed big-endian into four U32 words.
Usage: scripts/font-to-bend.py assets/fonts/spleen-8x16.bdf > src/gfx/font.bend
"""
import sys

path = sys.argv[1]
glyphs = {}
enc = None
rows = None
bbx = None
for line in open(path, encoding="latin-1"):
    parts = line.split()
    if not parts:
        continue
    if parts[0] == "ENCODING":
        enc = int(parts[1])
    elif parts[0] == "BBX":
        bbx = [int(x) for x in parts[1:5]]
    elif parts[0] == "BITMAP":
        rows = []
    elif parts[0] == "ENDCHAR":
        if enc is not None and 0 < enc < 0x10000 and rows is not None and len(rows) == 16:
            glyphs[enc] = rows
        enc, rows = None, None
    elif rows is not None:
        rows.append(int(parts[0], 16) & 0xFF)

def words(rs):
    return [(rs[i] << 24) | (rs[i + 1] << 16) | (rs[i + 2] << 8) | rs[i + 3] for i in range(0, 16, 4)]

out = []
out.append("import Base\n")
out.append("# Spleen 8x16 (BSD-2-Clause, Frederic Cambus; assets/fonts/SPLEEN-LICENSE).")
out.append("# Generated by scripts/font-to-bend.py; do not edit by hand.")
out.append("# A glyph is 16 rows of 8 pixels, four rows per word, top row in the high byte.\n")
out.append("type Glyph is Data:\n  Glyph{a: U32, b: U32, c: U32, d: U32}\n")
out.append("type Entry is Data:\n  Entry{cp: U32, glyph: Glyph}\n")
box = "Glyph{2122219134, 1111638594, 1111638594, 2122219134}"
out.append("def Font.box() -> Glyph:\n  " + box + "\n")
out.append("# code points below 256: a direct match")
out.append("def Font.low(cp: Nat) -> Glyph:\n  match cp:")
for code in sorted(c for c in glyphs if c < 256):
    w = words(glyphs[code])
    out.append(f"    case {code}n:\n      Glyph{{{w[0]}, {w[1]}, {w[2]}, {w[3]}}}")
out.append("    case _:\n      Font.box()\n")
high = sorted(c for c in glyphs if c >= 256)
out.append("# the rest (box drawing, arrows, symbols), in code point order")
out.append("def Font.high() -> List<&2, Entry>:\n  [")
out.append(",\n".join(f"    Entry{{{c}, Glyph{{{', '.join(str(x) for x in words(glyphs[c]))}}}}}" for c in high))
out.append("  ]\n")
out.append("""def Font.hit(es: List<&2, Entry>, +cp: U32) -> Bool:
  match es:
    case Entry{c, _} <> _:
      U32.is_eq(c, cp)
    case Nil{}:
      False{}

def Font.past(es: List<&2, Entry>, +cp: U32) -> Bool:
  match es:
    case Entry{c, _} <> _:
      U32.is_gt(c, cp)
    case Nil{}:
      True{}

# walk the sorted list; stop at the entry or once past it
def Font.find(es: List<&2, Entry>, hit: Bool, past: Bool, +cp: U32) -> Glyph:
  match es hit past:
    case Entry{_, g} <> _ True{} _:
      g
    case _ False{} True{}:
      Font.box()
    case _ <> +t False{} False{}:
      Font.find(t, Font.hit(t, cp), Font.past(t, cp), cp)
    case Nil{} _ _:
      Font.box()

def Font.glyph.k(low: Bool, +cp: U32) -> Glyph:
  match low:
    case True{}:
      Font.low(U32.to_nat(cp))
    case False{}:
      Font.find(Font.high(), Font.hit(Font.high(), cp), Font.past(Font.high(), cp), cp)

# the glyph for a code point (a hollow box for any the font lacks)
def Font.glyph(+cp: U32) -> Glyph:
  Font.glyph.k(U32.is_lt(cp, 256), cp)

# whether pixel (x, y) of a glyph is set (x 0..7, y 0..15)
def Font.bit.k(w: U32, +y: U32, +x: U32) -> Bool:
  U32.is_ne(U32.and(U32.shrn(w, U32.to_nat((((3 - U32.and(y, 3) : U32) * 8 : U32) + (7 - x : U32) : U32))), 1), 0)

def Font.bit(g: Glyph, +x: U32, +y: U32) -> Bool:
  match g:
    case Glyph{a, b, c, d}:
      Font.bit.k(Font.row4(U32.shr(U32.shr(y)), a, b, c, d), y, x)

def Font.row4(+q: U32, a: U32, b: U32, c: U32, d: U32) -> U32:
  Bool.pick(U32, U32.is_eq(q, 0), a, Bool.pick(U32, U32.is_eq(q, 1), b, Bool.pick(U32, U32.is_eq(q, 2), c, d)))
""")
print("\n".join(out))
print(f"# {len(glyphs)} glyphs", file=sys.stderr)
