#!/usr/bin/env python3
"""Turn the Hershey "simplex roman" (romans) glyphs into src/core/strokefont.bend.

The Hershey fonts are public domain (A. V. Hershey, U.S. National Bureau of
Standards, 1967). The JHF file is fetched from a pinned commit of
https://github.com/kamalmostafa/hershey-fonts (where romans is `futural.jhf`)
and checked against its SHA-256, or read from a local path.

Usage: scripts/strokefont-to-bend.py [futural.jhf]

Rewrites src/core/strokefont.bend: the glyph table is regenerated, and the
hand-written layout code after the MARKER line is kept as it is.

JHF format: per glyph, a 5-char id, a 3-char vertex count, then that many
coordinate pairs as characters offset from 'R' (x right, y down). The first
pair is the left and right bearing; " R" lifts the pen. Capitals span
y = -12 (top) .. 9 (baseline), so 21 units are one text height.
"""
import hashlib
import os
import sys
import urllib.request

URL = ("https://raw.githubusercontent.com/kamalmostafa/hershey-fonts/"
       "1356bf2f83d380fcef68c887e88675eb9d445d86/hershey-fonts/futural.jhf")
SHA256 = "4958a1d06ea04709feb530deaab53d1efa1285d0d3e92a4a3edd74d279871ced"

if len(sys.argv) > 1:
    data = open(sys.argv[1], "rb").read()
else:
    data = urllib.request.urlopen(URL, timeout=30).read()
if hashlib.sha256(data).hexdigest() != SHA256:
    sys.exit("futural.jhf: unexpected SHA-256")
text = data.decode("ascii")

# join wrapped lines: a glyph holds 8 header chars plus 2 per vertex
records = []
buf = ""
for line in text.split("\n"):
    line = line.rstrip("\r")
    buf += line
    if len(buf) < 8:
        continue
    n = int(buf[5:8])
    if len(buf) >= 8 + 2 * n:
        records.append(buf[: 8 + 2 * n])
        buf = ""
assert len(records) >= 95, len(records)
records = records[:95]  # 32..126 (the 96th is a filled DEL block)

def decode(rec):
    n = int(rec[5:8])
    body = rec[8: 8 + 2 * n]
    left, right = ord(body[0]) - 82, ord(body[1]) - 82
    strokes, cur = [], []
    for i in range(2, len(body), 2):
        a, b = body[i], body[i + 1]
        if a == " " and b == "R":
            if cur:
                strokes.append(cur)
            cur = []
        else:
            cur.append((ord(a) - 82, ord(b) - 82))
    if cur:
        strokes.append(cur)
    return left, right, strokes

glyphs = {32 + i: decode(r) for i, r in enumerate(records)}

# a few Latin-1 signs common in part values, built from the glyphs above
ul, ur, us = glyphs[ord("u")]
glyphs[181] = (ul, ur, us + [[(us[0][0][0], us[0][0][1]), (us[0][0][0], 16)]])  # micro: u with a tail
glyphs[176] = (-5, 5, [[(-1, -12), (-2, -11), (-2, -9), (-1, -8), (1, -8), (2, -9), (2, -11), (1, -12), (-1, -12)]])  # degree
glyphs[177] = (-13, 13, [[(0, -9), (0, 7)], [(-8, -1), (8, -1)], [(-8, 9), (8, 9)]])  # plus-minus
# Ohm (U+03A9) is mapped onto this slot in Stroke.glyph
glyphs[937] = (-10, 11, [[(-7, 9), (-3, 9), (-6, 3), (-7, -1), (-7, -5), (-6, -9), (-3, -11), (0, -12), (1, -12),
                          (4, -11), (7, -9), (8, -5), (8, -1), (7, 3), (4, 9), (8, 9)]])

B = 64  # bias: coordinates are stored as unsigned (value + 64)

def pts(stroke):
    return "[" + ", ".join(f"GP{{{x + B}, {y + B}}}" for x, y in stroke) + "]"

def glyph(g):
    l, r, ss = g
    return f"Glyph{{{l + B}, {r + B}, [" + ", ".join(pts(s) for s in ss) + "]}"

out = []
out.append("""import Base
import ./board.bend as B

# A stroke (vector) font for schematic and board text: the Hershey simplex
# roman glyphs (public domain; A. V. Hershey, NBS 1967), close to the
# stroke font KiCad draws with. Generated by scripts/strokefont-to-bend.py;
# do not edit the glyph table by hand.
#
# Glyph units: x right, y down, capitals from y = -12 to the baseline at
# y = 9 (21 units = one text height). Coordinates are stored plus 64.

type GP is Data:
  GP{x: U32, y: U32}

# left and right bearings, and the strokes (polylines)
type Glyph is Data:
  Glyph{l: U32, r: U32, strokes: List<&2, List<&2, GP>>}
""")
box = glyph((-8, 8, [[(-5, -12), (5, -12), (5, 9), (-5, 9), (-5, -12)]]))
out.append("# a hollow box for code points the font lacks")
out.append("def Stroke.box() -> Glyph:\n  " + box + "\n")
out.append("# printable ASCII and a few Latin-1 signs")
out.append("def Stroke.low(cp: Nat) -> Glyph:\n  match cp:")
for code in sorted(c for c in glyphs if c < 256):
    out.append(f"    case {code}n:\n      {glyph(glyphs[code])}")
out.append("    case _:\n      Stroke.box()\n")
out.append("def Stroke.ohm() -> Glyph:\n  " + glyph(glyphs[937]) + "\n")
out.append("""def Stroke.glyph.k(low: Bool, ohm: Bool, +cp: U32) -> Glyph:
  match low ohm:
    case True{} _:
      Stroke.low(U32.to_nat(cp))
    case False{} True{}:
      Stroke.ohm()
    case False{} False{}:
      Stroke.box()

# the glyph for a code point
def Stroke.glyph(+cp: U32) -> Glyph:
  Stroke.glyph.k(U32.is_lt(cp, 256), Bool.or(U32.is_eq(cp, 937), U32.is_eq(cp, 8486)), cp)
""")
MARKER = "# ---- layout (hand-written; scripts/strokefont-to-bend.py keeps this part) ----"
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "core", "strokefont.bend")
tail = ""
if os.path.exists(path):
    old = open(path).read()
    if MARKER in old:
        tail = old[old.index(MARKER):]
if not tail:
    sys.exit(path + ": no hand-written layout part (" + MARKER + ")")
open(path, "w").write("\n".join(out) + "\n" + tail)
print(f"# {len(glyphs)} glyphs", file=sys.stderr)
